run:
  # timeout for analysis, e.g. 30s, 5m, default is 1m
  deadline: 2m
linters:
  enable-all: true
  disable:
    - scopelint
    - dupl
linters-settings:
  misspell:
    locale: US
issues:
  max-same: 0
  max-per-linter: 0
  exclude-use-default: false
  exclude:
    # gosec: Duplicated errcheck checks
    - G104
    # gosec: Variable url
    - G107
    # gosec: md5 needed by CDEK
    - G501
    # gosec: md5 needed by CDEK
    - G401